# Menus
menu:
  Home: .
  Archives: archives
  Works: works
#   Categories: categories
#   Tags: tags
  About: about

# Customize
customize:
    logo:
        enabled: true
        width: 40
        height: 40
        url: images/bloglogo.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/bloglogo3.jpg
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: Jian Hou
        author_title: Learning Game Dev
        location: Dalian, China
        follow: https://github.com/hjmeteor/
    highlight: monokai
    sidebar: right # sidebar position, options: left, right or leave it empty
    thumbnail: false # enable posts thumbnail, options: true, false
    favicon: css/images/logo.ico
    social_links:
        github: http://github.com/hjmeteor/
        # twitter: https://twitter.com/Meteorssssss
        # facebook: /
        # weibo: www.baidu.com
        # zhihu: https://www.zhihu.com/people/Meteorssssss/activities
        steam: http://steamcommunity.com/id/WuKong_HJ/
        instagram: https://www.instagram.com/meteorssssss/
    social_link_tooltip: true # enable the social link tooltip, options: true, false

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    # - tag
    - tagcloud
    # - links

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: true # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: roetem # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here
    facebook: # enter true to enable
    isso: # enter the domain name of your own comment isso server eg. comments.example.com
    changyan: # please fill in `appid` and `conf` to enable
        appid:
        conf:
    gitment:
        owner: #your github ID
        repo: #the repo to store comments
        #Register an OAuth application, and you will get a client ID and a client secret.
        client_id: #your client ID
        client_secret: #your client secret

# Share
share: jiathis # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    lightgallery: true # options: true, false
    justifiedgallery: true # options: true, false
    google_analytics: UA-102947855-1
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key
    mathjax: true # options: true, false

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
